apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: kyndryl-flower-app-deployment 
spec: # Behaviour of the Deployment 
  replicas: 3
  selector:
    matchLabels:
      app: web
  template: # Pod Defination
    metadata:
      labels:
        app: web 
    spec: # Define the behaviour of the Pod 
      containers:
        - name: flower-app 
          image: muralisocial123/kyndrl-flower-app:v1.1.0
          ports:
            - containerPort: 3015
--- 
apiVersion: v1 
kind: Service
metadata:
  name: flower-app-svc
spec:
  selector:
    app: web
  ports:
  - port: 3016 # User Defined Port - DevOps Team Will decide this 
    targetPort: 3015
  type: LoadBalancer  
            
